[package]
edition = "2021"
name = "benchmarks"
version = "0.1.0"

[[bin]]
name = "ibe"
path = "ibe/src/main.rs"

[dependencies]
# FIXME: use versioned `canbench` when https://github.com/dfinity/canbench/pull/156 is merged and released
canbench-rs = { git = "https://github.com/dfinity/canbench.git", rev = "e8df43674c3bd635e49929094175294f148e8f41", optional = true }
candid = "0.10.0"
getrandom = { version = "0.2", features = ["custom"] }
hex = { workspace = true }
ic-cdk = { workspace = true }
ic-vetkeys = { path = "../ic_vetkeys" }

