[workspace]
members = ["backend"]
resolver = "2"

[workspace.dependencies]
ic-cdk = "0.19.0"
ic-stable-structures = "0.7.0"
ic-vetkeys = { path = "../../../backend/rs/ic_vetkeys" }

[profile.release]
lto = true
opt-level = 'z'
panic = 'abort'